apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"order"},"name":"order-by-yaml","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"order"}},"template":{"metadata":{"labels":{"app":"order"}},"spec":{"containers":[{"image":"jinyoung/monolith-order:v20210504","name":"order","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2025-06-17T03:19:54Z"
  generation: 1
  labels:
    app: order
  name: order-by-yaml
  namespace: default
  resourceVersion: "39028"
  uid: c8d00f44-45ef-450e-9adb-31ec54d051bc
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: order
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order
    spec:
      containers:
      - image: jinyoung/monolith-order:v20210504
        imagePullPolicy: IfNotPresent
        name: order
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-06-17T03:19:56Z"
    lastUpdateTime: "2025-06-17T03:19:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-17T03:19:55Z"
    lastUpdateTime: "2025-06-17T03:19:56Z"
    message: ReplicaSet "order-by-yaml-7d545bb4f7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
